// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhfyftwqxclegpoojenm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoZnlmdHdxeGNsZWdwb29qZW5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDI5MTcsImV4cCI6MjA2NDg3ODkxN30.EBkVjrnyhqMUT7qA8P8vRriDCeIsX7yQBJG467dcZHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);